// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Outfit } from 'next/font/google'
// import Provider from "./provider";
// import { ClerkProvider } from "@clerk/nextjs";
// import { Toaster } from "sonner";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// const outfit = Outfit({subsets:['latin']})

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <body className={outfit.className}
       
//       >
//         <Provider>
//         {children}
//         <Toaster />
//         </Provider>
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }


// app/layout.tsx
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Footer from "./_components/Footer";


export const metadata: Metadata = {
  title: "PDF-Insight",
  description: "Developed by empsloc",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <Provider>
            <div className="flex flex-col min-h-screen">
              {/* Main content grows to fill screen */}
              <main className="flex-grow">{children}</main>

              {/* Footer always at bottom */}
              <Footer />
            </div>
            <Toaster />
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
